### ISSUE TITLE
Not Working 

### ISSUE THREAD

**Issue by mayankwadhwa** [mehdidc/pomodoro#1]
Hey every time I used any command it is showing this message
![screen shot 2017-12-19 at 10 05 48 am](https://user-images.githubusercontent.com/17674962/34140971-3715db56-e4a4-11e7-8597-a340165f0f91.png)

**Comment by kav2k** [comment]
@mayankwadhwa You're trying to run a Python 3 only script with Python 2.

You'll need to install Python 3 (e.g. [through Homebrew](http://docs.python-guide.org/en/latest/starting/install3/osx/)) and probably modify the first line of the script to read

```python
#!/usr/bin/env python3
```

For @mehdidc - it may be useful to modify that line in the official source as well. (Or remove Python 3 only syntax)

**Comment by mehdidc** [comment]
@mayankwadhwa , @kav2k Thanks !  I will make it compatible with python 2 as well.

**Comment by mehdidc** [comment]
@mayankwadhwa It should work now for python 2 as well, could you please retry ? Thanks

**Comment by daiwai** [comment]
Trying to run on Ubuntu 16.04 gave me:

`Traceback (most recent call last):
  File "/usr/local/bin/pomodoro", line 4, in <module>
    __import__('pkg_resources').run_script('pomodoro==0.1', 'pomodoro')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/pomodoro-0.1-py2.7.egg/EGG-INFO/scripts/pomodoro", line 4, in <module>
    from clize import run
  File "/usr/local/lib/python2.7/dist-packages/clize-4.0.2-py2.7.egg/clize/__init__.py", line 7, in <module>
    from clize.parser import Parameter
  File "/usr/local/lib/python2.7/dist-packages/clize-4.0.2-py2.7.egg/clize/parser.py", line 1057, in <module>
    class CliBoundArguments(object):
  File "/usr/lib/python2.7/dist-packages/attr/_make.py", line 200, in attributes
    return wrap(maybe_cl)
  File "/usr/lib/python2.7/dist-packages/attr/_make.py", line 184, in wrap
    _transform_attrs(cl, these)
  File "/usr/lib/python2.7/dist-packages/attr/_make.py", line 137, in _transform_attrs
    .format(a=a)
ValueError: No mandatory attributes allowed after an attribute with a default value or factory.  Attribute in question: Attribute(name='posparam', default=NOTHING, validator=None, repr=True, cmp=True, hash=True, init=False, convert=None)
`

However I ran the setup.py script again with python3 and now it seems to work.

**Comment by mayankwadhwa** [comment]
Thanks man @mehdidc its working now

**Comment by mehdidc** [comment]
Great ! I will close this issue, and create a new one for @daiwai
