### ISSUE TITLE
how to quit the program or pause it?  also pomostats not working (noob user questions)

### ISSUE THREAD

**Issue by arooni** [mehdidc/pomodoro#14]
so i run pomodoro 60 5; i got to the alarm.  then i hit ctrl c

1) is there a better way to stop it?  
2) is there an option to pause the pomodoros?
3) it seems if i run ctrl c i cant seem to recover the pomdoro stats.  

thanks!

^CInterrupting
[I]  ~  pomostat thisweek
Traceback (most recent call last):
  File "/usr/local/bin/pomostat", line 4, in <module>
    __import__('pkg_resources').run_script('pomodoro==0.1', 'pomostat')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/pomodoro-0.1-py2.7.egg/EGG-INFO/scripts/pomostat", line 157, in <module>
    run(main)
  File "/usr/local/lib/python2.7/dist-packages/sigtools-2.0.1-py2.7.egg/sigtools/modifiers.py", line 158, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/clize-4.0.3-py2.7.egg/clize/runner.py", line 360, in run
    ret = cli(*args)
  File "/usr/local/lib/python2.7/dist-packages/clize-4.0.3-py2.7.egg/clize/runner.py", line 220, in __call__
    return func(*posargs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sigtools-2.0.1-py2.7.egg/sigtools/modifiers.py", line 158, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pomodoro-0.1-py2.7.egg/EGG-INFO/scripts/pomostat", line 108, in main
    D = D[D.start >= last_monday]
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.23.0rc2-py2.7-linux-x86_64.egg/pandas/core/ops.py", line 1201, in wrapper
    pd.DatetimeIndex)
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.23.0rc2-py2.7-linux-x86_64.egg/pandas/core/ops.py", line 1098, in dispatch_to_index_op
    result = op(left_idx, right)
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.23.0rc2-py2.7-linux-x86_64.egg/pandas/core/indexes/datetimes.py", line 133, in wrapper
    (type(other), str(other)))
TypeError: <type 'datetime.date'> type object 2018-04-30

**Comment by mehdidc** [comment]
Hello @arooni ,

thanks for raising this issue.

1) Currently the only way to stop it is ctrl+c
2) No there is no way currently, I would say that pomodoros are not meant to be paused
3) I would say that it is compatible with the original idea of pomodoro, that you either finish a full
pomodoro session (and it is recorded) or you cancel it (in that case it is not recorded)

Let me know what you think

The error  happens because there is no recorded pomodoro for the week, but I will make a better error message, thanks

**Comment by arooni** [comment]
I appreciate your response:  

1) Let's say I have to take a call that I didn't expect or need to run an errand.  I'd like *not* to count the time I'm not really working on productive things as a POM.  So if I could 'pause' a POM I could take care of that busywork and then resume the POM when I was done.  Or perhaps you'd like to force me to restart the POM which I'd also be amenable to (or let the user pick how strict they want to take it)
2) I have received that error with the stats part even after completing a task or two... so I'm not sure why I'm getting it.  I was hoping to get motivated by seeing the POMs recorded and beat my previous record.

**Comment by arooni** [comment]
Looks like upgrading via pip allows me to see that I haven't worked any POMs even though I thought I recorded at least one.  I'll run this a bit and see how it goes ;)  thanks!
